import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { generateText } from "@/lib/ai"

/**
 * @openapi
 * /api/digest:
 *   get:
 *     summary: Get the AI-generated daily digest summarizing top discussions, matches, and standings
 *     tags: [Digest]
 *     parameters:
 *       - in: query
 *         name: date
 *         schema:
 *           type: string
 *           format: date
 *         example: "2026-03-08"
 *       - in: query
 *         name: force
 *         schema:
 *           type: boolean
 *         example: false
 *     responses:
 *       200:
 *         description: Daily digest content
 *       404:
 *         description: No digest found for the requested date
 *       500:
 *         description: Internal server error
 */

/**
 * GET /api/digest
 *
 * User Story:
 *   As a user, I want to read a daily digest post generated by AI that
 *   summarizes the top discussions, recorded matches, and standings,
 *   allowing me to quickly catch up on recent events.
 *
 * Behavior:
 * - Returns today's cached digest if it already exists.
 * - Otherwise gathers fresh data, asks the AI to summarize it,
 *   caches the result, and returns it.
 *
 * Query params:
 *   ?date=YYYY-MM-DD   (optional, defaults to today)
 *   ?force=true         (optional, regenerate even if cached)
 */

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url)
    const dateParam = searchParams.get("date")
    const force = searchParams.get("force") === "true"

    const todayStr = new Date().toISOString().slice(0, 10) // "YYYY-MM-DD"
    const today = dateParam ?? todayStr

    // ── Return cached digest unless forced ────────────
    if (!force) {
      const existing = await prisma.dailyDigest.findUnique({
        where: { date: today },
      })
      if (existing) {
        return NextResponse.json(existing)
      }
    }

    // ── Past dates with no cache → 404 ───────────────
    // Only generate fresh digests for today. Historical dates without a
    // cached entry simply don't exist yet.
    if (today !== todayStr) {
      return NextResponse.json(
        { error: `No digest found for ${today}` },
        { status: 404 }
      )
    }

    // ── Gather data for the digest ────────────────────

    // 1. Recent match results (last 3 days)
    const threeDaysAgo = new Date()
    threeDaysAgo.setDate(threeDaysAgo.getDate() - 3)

    const recentMatches = await prisma.match.findMany({
      where: {
        matchDate: { gte: threeDaysAgo },
        status: "FINISHED",
      },
      include: {
        homeTeam: { select: { name: true, shortName: true } },
        awayTeam: { select: { name: true, shortName: true } },
      },
      orderBy: { matchDate: "desc" },
      take: 10,
    })

    // 2. Current standings (top 6)
    const year = new Date().getFullYear();
    const currentSeason = `${year - 1}-${year}`; // e.g. "2024-2025"
    const standings = await prisma.standing.findMany({
      where: { season: currentSeason, type: "TOTAL" },
      include: { team: { select: { name: true } } },
      orderBy: { position: "asc" },
      take: 6,
    })

    // 3. Trending discussion threads (most posts overall)
    const trendingThreads = await prisma.thread.findMany({
      where: { isHidden: false },
      include: {
        author: { select: { username: true } },
        _count: { select: { posts: true } },
        tags: { include: { tag: true } },
      },
      orderBy: { posts: { _count: "desc" } },
      take: 5,
    })

    // ── Build the text block for summarization ────────

    let dataBlock = ""

    // Matches section
    if (recentMatches.length > 0) {
      dataBlock += "Recent Premier League match results: "
      dataBlock += recentMatches
        .map(
          (m) =>
            `${m.homeTeam.name} ${m.homeScore ?? "?"}-${m.awayScore ?? "?"} ${m.awayTeam.name} (${m.matchDate.toISOString().slice(0, 10)})`
        )
        .join(". ")
      dataBlock += ". "
    } else {
      dataBlock += "No recent match results in the last 3 days. "
    }

    // Standings section
    if (standings.length > 0) {
      dataBlock += "Current Premier League top standings: "
      dataBlock += standings
        .map(
          (s) =>
            `${s.position}. ${s.team.name} - ${s.points}pts (P${s.played} W${s.won} D${s.drawn} L${s.lost})`
        )
        .join(". ")
      dataBlock += ". "
    }

    // Discussions section
    if (trendingThreads.length > 0) {
      dataBlock += "Trending discussions on SportsDeck: "
      dataBlock += trendingThreads
        .map(
          (t) =>
            `"${t.title}" by ${t.author.username ?? "anonymous"} with ${t._count.posts} posts, tags: [${t.tags.map((tt) => tt.tag.name).join(", ")}]`
        )
        .join(". ")
      dataBlock += ". "
    }

    // ── Generate AI summary ──────────────────────────
    let content: string

    const aiResult = await generateText(dataBlock)

    if (aiResult?.generatedText) {
      // Wrap the AI-generated summary with a nice header
      const dateDisplay = new Date(today).toLocaleDateString("en-US", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      })

      content = `# SportsDeck Daily Digest — ${dateDisplay}\n\n${aiResult.generatedText}`
    } else {
      // Fallback: build a structured digest without AI
      content = buildFallbackDigest(today, recentMatches, standings, trendingThreads)
    }

    // ── Cache and return ─────────────────────────────
    const digest = await prisma.dailyDigest.upsert({
      where: { date: today },
      update: { content, generatedAt: new Date() },
      create: { date: today, content },
    })

    return NextResponse.json(digest)
  } catch (error) {
    console.error("Digest generation error:", error)
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    )
  }
}

// ─── Fallback digest when AI is unavailable ──────────────────────

function buildFallbackDigest(
  date: string,
  matches: Array<{
    homeTeam: { name: string; shortName: string }
    awayTeam: { name: string; shortName: string }
    homeScore: number | null
    awayScore: number | null
    matchDate: Date
  }>,
  standings: Array<{
    position: number
    team: { name: string }
    points: number
    played: number
    won: number
    drawn: number
    lost: number
  }>,
  threads: Array<{
    title: string
    author: { username: string | null }
    _count: { posts: number }
    tags: Array<{ tag: { name: string } }>
  }>
): string {
  const dateDisplay = new Date(date).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  let md = `# SportsDeck Daily Digest — ${dateDisplay}\n\n`

  // Matches
  md += "## Recent Match Results\n"
  if (matches.length > 0) {
    for (const m of matches) {
      md += `- **${m.homeTeam.name}** ${m.homeScore ?? "?"} – ${m.awayScore ?? "?"} **${m.awayTeam.name}** (${m.matchDate.toISOString().slice(0, 10)})\n`
    }
  } else {
    md += "No recent match results.\n"
  }
  md += "\n"

  // Standings
  md += "## Standings Snapshot\n"
  if (standings.length > 0) {
    md += "| # | Team | Pts | P | W | D | L |\n"
    md += "|---|------|-----|---|---|---|---|\n"
    for (const s of standings) {
      md += `| ${s.position} | ${s.team.name} | ${s.points} | ${s.played} | ${s.won} | ${s.drawn} | ${s.lost} |\n`
    }
  } else {
    md += "Standings data unavailable.\n"
  }
  md += "\n"

  // Discussions
  md += "## Trending Discussions\n"
  if (threads.length > 0) {
    for (const t of threads) {
      md += `- "${t.title}" by ${t.author.username ?? "anonymous"} (${t._count.posts} posts) [${t.tags.map((tt) => tt.tag.name).join(", ")}]\n`
    }
  } else {
    md += "No trending discussions today.\n"
  }

  return md
}
